server:
  port: 8092

spring:
  application:
    name: secflag-demo
  datasource:
    username: user
    password: password
    url:  jdbc:postgresql://localhost:5432/secflag
  flyway:
    url: jdbc:postgresql://localhost:5432/secflag
    user: user
    password: password