DROP TABLE IF EXISTS event;
CREATE TABLE event (
    event_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name           VARCHAR(255) NOT NULL,
    event_description    VARCHAR(255) NOT NULL,
    version              integer NOT NULL
);